print("Hello World")
print("Welcome to Python, what is your name?")
name = input()
print("It is very nice to meet you, " + name)
print("So... " + name, " What is your age?")
age = int(input())
print("Oh your an old one")
print("You will be " + str(int(age) + 1), " in one year!!")
